### PR TITLE
Add acceptance tests

### PR DESCRIPTION
**Pull request by LinqLover**
[smalltalkCI](https://github.com/LinqLover/poppy-print/actions/workflows/tests.yml)

### CODE REVIEW

**Comment by LinqLover** [comment]
Ha, just spotted another bug in the Compiler:

```smalltalk
Compiler new compileNoPattern: '2. "comment"' in: UndefinedObject notifying: nil ifFail: nil
```

It skips the trailing comment:

```smalltalk
DoIt
	^ 2
```

On it ...

**Comment by tom95** [comment]
Comments are quite a mess at the moment. The PPParser subclass of Parser is trying to make sure we're at least not losing any. In theory, the subclass should also handle this already, see `PPFormatterTest>>#testMultipleComments`.

**Comment by LinqLover** [comment]
Hm, but I think this issue should be fixed in the regular Parser as well, don't you? In the test I added, PoppyPrint formats the string correctly, but when parsing it again afterward, the comment is lost (see `PPFormatterTest >> #canFormatMethod:`).

**Comment by LinqLover** [comment]
@tom95 Do you think we should give these tests a try? Actually, they are rather smoke tests than acceptance tests but I think they can always be helpful to quickly detect large regressions. Apart from that, the [Transcript output](https://github.com/LinqLover/poppy-print/runs/2288584292?check_suite_focus=true#step:4:189) gives an exhaustive overview of all methods that still fail to be poppy-printed correctly. I have already reported most of them as separate issues. 

The CI is still red because of two methods on Object that currently styled incorrectly as reported in #8. If you agree with the rest of the patch, I would just exclude these methods as a workaround, or flag the test as an expected failure.

**Comment by tom95** [comment]
Yeah I think it's a great idea!

I'm not sure if we need the 1% cut-off for failing the global test. I would vote for either

1. just run it without ever failing
2. store the selectors in the base image that are failing so that we get notified of regressions

Thank you for investigating these in such detail. In a week or so, I'll also finally be able to contribute again :)

**Comment by LinqLover** [comment]
Thanks for the feedback! :-)

> 2. store the selectors in the base image that are failing so that we get notified of regressions

That would be a *huge* list at the moment because some concepts (e.g. #8 #17) just are not supported at the moment. And this list would be brittle if the base image is more likely to change than PoppyPrint is.

If we just ran the test without ever failing, it would not work as an automatic smoke test on the CI any longer. My idea was that when someone breaks a certain feature such as FFI again, a threshold would be exceeded and you would get a green bar. But on the other hand, this could break, too, when a large amount of methods in the base image is deleted. I don't know. :-)

BTW, at the moment in my image, the actual failure rate was about 0.3%, I have not tested it in a clean trunk image.

**Comment by tom95** [comment]
Without having looked at the list, could we generate a large part of that list by "feature testing" a method?

Otherwise, I do like the idea of having the smoke test enough such that I would vote to keep the arbitrary cut-off in and see how we'll fare with it in the future.

**Comment by LinqLover** [comment]
> Without having looked at the list, could we generate a large part of that list by "feature testing" a method?

Yessss ... This might be possible but sounds at least as complicated to me as fixing the actual bugs. At least from my perspective (I'm not familiar with your implementation). :D

**Comment by tom95** [comment]
That's fair. I'm voting to take it in as-is then. Could you add the expected failure for the two Object methods you mentioned, such that CI will be green for the moment? I'll press merge right after :)

**Comment by LinqLover** [comment]
Done, ready to merge :-)

**Pull request merged**
